[package]
name = "helix-prover"
version = "0.1.0"
edition = "2021"

[dependencies]
helix-core = { path = "../helix-core" }
helix-avm = { path = "../helix-avm" }
helix-circuits = { path = "../helix-circuits" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8"
num_cpus = "1.16"
sha2 = "0.10"
num-bigint = "0.4"

