{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name | default "helix" }}
  labels:
    {{- include "helix.labels" . | nindent 4 }}
    name: {{ .Values.namespace.name | default "helix" }}
{{- end }}
