// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

import "forge-std/Test.sol";
import "../src/verification/PoseidonHasher.sol";

/// @title PoseidonCrossLanguageTest
/// @notice Verifies that PoseidonHasher.sol produces bit-identical output to
///         helix-circuits poseidon_hash_two() for the same inputs.
/// @dev The expected values in this file are computed by Rust (see
///      helix/tests/integration/cross_crate_consistency.rs test_poseidon_cross_language_vectors).
///      If either implementation changes, BOTH this test and the Rust test will fail.
contract PoseidonCrossLanguageTest is Test {
    /// @notice Vector 1: hashTwo(0, 0) — simplest case
    function test_PoseidonHashTwo_ZeroZero() public pure {
        uint256 result = PoseidonHasher.hashTwo(0, 0);
        // Must be nonzero (Poseidon of zero inputs still permutes through round constants)
        assertTrue(result != 0, "Poseidon(0,0) should be nonzero");
        // Cross-language check: this value must match Rust poseidon_hash_two(Fr::zero(), Fr::zero())
        // If this assertion fails, the Rust and Solidity Poseidon implementations diverge.
        assertEq(
            result,
            POSEIDON_ZERO_ZERO,
            "Poseidon(0,0) cross-language mismatch - Rust and Solidity disagree"
        );
    }

    /// @notice Vector 2: hashTwo(1, 2) — small nonzero inputs
    function test_PoseidonHashTwo_OneTwo() public pure {
        uint256 result = PoseidonHasher.hashTwo(1, 2);
        assertEq(
            result,
            POSEIDON_ONE_TWO,
            "Poseidon(1,2) cross-language mismatch"
        );
    }

    /// @notice Vector 3: computeErrorChecksum(10, 1, 0, 1e18)
    ///         This is the exact call the coordinator makes for error_bound=10, step=1, model=0.
    function test_PoseidonErrorChecksum_Default() public pure {
        uint256 result = PoseidonHasher.computeErrorChecksum(10, 1, 0, 1e18);
        assertEq(
            result,
            POSEIDON_CHECKSUM_DEFAULT,
            "computeErrorChecksum(10,1,0,1e18) cross-language mismatch"
        );
    }

    /// @notice Vector 4: computeErrorChecksum(100, 5, 3, 1e18)
    ///         Different model ID and step to exercise more of the hash.
    function test_PoseidonErrorChecksum_ModelThree() public pure {
        uint256 result = PoseidonHasher.computeErrorChecksum(100, 5, 3, 1e18);
        assertEq(
            result,
            POSEIDON_CHECKSUM_MODEL3,
            "computeErrorChecksum(100,5,3,1e18) cross-language mismatch"
        );
    }

    /// @notice Dump all test vectors so Rust side can capture them.
    ///         Run with: forge test --match-test test_DumpVectors -vvv
    function test_DumpVectors() public pure {
        uint256 v1 = PoseidonHasher.hashTwo(0, 0);
        uint256 v2 = PoseidonHasher.hashTwo(1, 2);
        uint256 v3 = PoseidonHasher.computeErrorChecksum(10, 1, 0, 1e18);
        uint256 v4 = PoseidonHasher.computeErrorChecksum(100, 5, 3, 1e18);

        // These are logged in verbose mode (-vvv) so they can be captured.
        // To update the Rust test vectors, run this test and copy the values.
        assert(v1 != 0);
        assert(v2 != 0);
        assert(v3 != 0);
        assert(v4 != 0);
    }

    // ========================================================================
    // Cross-language constants — set by running Rust side first, then pasting.
    // To regenerate: cargo test -p helix-tests test_poseidon_cross_language_vectors -- --nocapture
    // ========================================================================

    // Generated by: cargo test -p helix-circuits test_poseidon_cross_language_vectors -- --nocapture
    uint256 constant POSEIDON_ZERO_ZERO = 0x1b1710d0ee1af6c798f53464834cff0fd7178e925cc6657a504e7caf26a2007f;
    uint256 constant POSEIDON_ONE_TWO = 0x19bc7ec7cff2b4581536ccf74442e81863dc9ed2f1a30605cb3a4f02e131a71a;
    uint256 constant POSEIDON_CHECKSUM_DEFAULT = 0x0204efe9f237ccf072189fac1028111cf40e6467a2905b05a56a05904dd44a13;
    uint256 constant POSEIDON_CHECKSUM_MODEL3 = 0x1afc34a200ca5ab0bf02123b5e4a577e7b3e9e4d25e45d420c4c020104a00759;
}
