// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

import "./Halo2VerifierCore.sol";
import "./Halo2VerifyingKey.sol";
import "../interfaces/IHelixVerifier.sol";

/// @title Halo2Verifier
/// @notice Backward-compatible wrapper around the PSE-generated Halo2VerifierCore.
///         Deploys the core verifier and VK contract internally, then delegates
///         all verification calls to the core verifier with the embedded VK.
/// @dev The core verifier (Halo2VerifierCore.sol) and VK (Halo2VerifyingKey.sol)
///      are generated by PSE's halo2-solidity-verifier from the Rust circuit.
///      The core verifier reverts on invalid proofs (assembly revert(0,0)).
///      This wrapper catches those reverts and returns false instead, which is
///      required by the coordinator contracts' slashing logic.
contract Halo2Verifier is IHelixVerifier {
    /// @notice The PSE-generated core verifier contract
    Halo2VerifierCore public immutable core;

    /// @notice The VK contract address (deployed Halo2VerifyingKey)
    address public immutable vk;

    /// @notice Contract owner (deployer)
    address public immutable owner;

    /// @notice Tracks used proof hashes for replay prevention
    mapping(bytes32 => bool) public usedProofs;

    /// @notice Backward-compatible alias for usedProofs
    mapping(bytes32 => bool) public verifiedProofs;

    /// @notice Deploy wrapper with internally-created core verifier and VK
    constructor() {
        core = new Halo2VerifierCore();
        vk = address(new Halo2VerifyingKey());
        owner = msg.sender;
    }

    // ============ IHelixVerifier Interface ============

    /// @notice Verify a single ZK proof
    /// @dev Catches reverts from the core verifier assembly and returns false
    function verifyProof(
        bytes memory proof,
        uint256[] memory publicInputs
    ) external view override returns (bool isValid) {
        try core.verifyProof(vk, proof, publicInputs) returns (bool result) {
            return result;
        } catch {
            return false;
        }
    }

    // ============ Extended Verification Methods ============

    /// @notice Verify a proof and record it to prevent replay
    function verifyAndRecord(
        bytes memory proof,
        uint256[] memory publicInputs
    ) external returns (bool isValid) {
        bytes32 proofHash = keccak256(abi.encodePacked(proof, publicInputs));
        if (usedProofs[proofHash]) return false;

        bool valid;
        try core.verifyProof(vk, proof, publicInputs) returns (bool result) {
            valid = result;
        } catch {
            valid = false;
        }

        if (valid) {
            usedProofs[proofHash] = true;
            verifiedProofs[proofHash] = true;
        }
        return valid;
    }

    /// @notice Batch-verify multiple proofs
    function batchVerify(
        bytes[] memory proofs,
        uint256[][] memory publicInputsArray
    ) external view returns (bool allValid) {
        require(proofs.length > 0, "Empty batch");
        require(proofs.length == publicInputsArray.length, "Length mismatch");
        for (uint256 i = 0; i < proofs.length; i++) {
            try core.verifyProof(vk, proofs[i], publicInputsArray[i]) returns (bool result) {
                if (!result) return false;
            } catch {
                return false;
            }
        }
        return true;
    }

    /// @notice Batch-verify proofs with same structure
    function batchVerifyHomogeneous(
        bytes[] memory proofs,
        uint256[][] memory publicInputsArray
    ) external view returns (bool allValid) {
        require(proofs.length == publicInputsArray.length, "Length mismatch");
        for (uint256 i = 0; i < proofs.length; i++) {
            try core.verifyProof(vk, proofs[i], publicInputsArray[i]) returns (bool result) {
                if (!result) return false;
            } catch {
                return false;
            }
        }
        return true;
    }

    // ============ Gas Estimation ============

    /// @notice Estimate gas for single proof verification
    function estimateVerifyGas(
        bytes memory proof,
        uint256[] memory publicInputs
    ) external view returns (uint256 gasUsed) {
        uint256 gasBefore = gasleft();
        try core.verifyProof(vk, proof, publicInputs) {} catch {}
        gasUsed = gasBefore - gasleft();
    }

    /// @notice Estimate gas for batch proof verification
    function estimateBatchVerifyGas(
        bytes[] memory proofs,
        uint256[][] memory publicInputsArray
    ) external view returns (uint256 totalGas, uint256 perProofGas) {
        require(proofs.length > 0, "Empty batch");
        require(proofs.length == publicInputsArray.length, "Length mismatch");
        uint256 gasBefore = gasleft();
        for (uint256 i = 0; i < proofs.length; i++) {
            try core.verifyProof(vk, proofs[i], publicInputsArray[i]) {} catch {}
        }
        totalGas = gasBefore - gasleft();
        perProofGas = totalGas / proofs.length;
    }
}

/// @notice Backward-compatible library (VK is now embedded in Halo2VerifyingKey contract)
library Halo2VKDefaults {
    function g2Generator() internal pure returns (uint256[4] memory sG2) {
        return sG2;
    }
}
