//! Halo2 Proof Verification Integration Tests.
//!
//! These tests verify that real Halo2 KZG proofs generated by
//! `MLTrainingProverV2` can be verified end-to-end through the node's
//! verification pipeline, including:
//!
//! - VerifierNode with VerifyAll policy (roles/verifier.rs)
//! - ProofVerifier with real Halo2 backend (training/verification.rs)
//!
//! Success Criteria:
//! 1. A real proof generated by MLTrainingProverV2 passes VerifierNode::verify_proof
//!    with VerifyAll policy.
//! 2. The same proof passes ProofVerifier::verify_gradient_proof.
//! 3. Random/fake proof bytes are rejected by both pipelines.

use ethers::types::U256;

use helix_prover::halo2curves::bn256::Fr;
use helix_prover::halo2curves::ff::Field;
use helix_prover::MLTrainingProverV2;

use helix_node::network::messages::PeerId;
use helix_node::roles::verifier::{VerificationPolicy, VerifierConfig, VerifierNode, VerifyResult};
use helix_node::sc_client::TrainingProofInputs;
use helix_node::training::verification::{ProofVerifier, VerificationConfig};

// ============================================================================
// Helper: build a small model, generate a real Halo2 proof, return proof bytes
// and public inputs suitable for the node pipeline.
// ============================================================================

/// Model dimensions used across all integration tests (small to keep proving fast).
const D_IN: usize = 2;
const D_HID: usize = 2;
const D_OUT: usize = 1;

/// Generates a real Halo2 KZG proof for a minimal 2-2-1 model.
///
/// Returns `(proof_bytes, public_inputs_fr, TrainingProofInputs)` or `None`
/// if the prover fails (e.g. resource-constrained CI).
fn generate_real_proof() -> Option<(Vec<u8>, Vec<Fr>, TrainingProofInputs)> {
    let prover = MLTrainingProverV2::new(D_IN, D_HID, D_OUT);

    let x = vec![Fr::from(1u64); D_IN];
    let target = vec![Fr::from(1u64); D_OUT];
    let w1 = vec![Fr::from(1u64); D_HID * D_IN];
    let b1 = vec![Fr::zero(); D_HID];
    let w2 = vec![Fr::from(1u64); D_OUT * D_HID];
    let b2 = vec![Fr::zero(); D_OUT];
    let lr = Fr::from(1u64);

    let witness = MLTrainingProverV2::build_witness(
        D_IN, D_HID, D_OUT,
        &x, &target,
        &w1, &b1, &w2, &b2,
        lr,
        1,            // step_number
        Fr::from(1u64), // base_error
    );

    let result = prover.prove(&witness).ok()?;

    // Verify the proof locally first to make sure it's valid
    assert!(
        prover.verify_result(&result),
        "Proof failed local verification — circuit / prover issue"
    );

    // Convert Fr public inputs to TrainingProofInputs (U256) for the node pipeline.
    // Public inputs layout: [old_hash_lo, old_hash_hi, new_hash_lo, new_hash_hi, loss, error, step, ...]
    let pi = &result.public_inputs;
    let fr_to_u256 = |fr: &Fr| -> U256 {
        use helix_prover::halo2curves::ff::PrimeField;
        let repr = fr.to_repr();
        U256::from_little_endian(repr.as_ref())
    };

    // pi has 8 elements: 7 on-chain + error_checksum
    let inputs = TrainingProofInputs {
        old_hash_lo: fr_to_u256(&pi[0]),
        old_hash_hi: fr_to_u256(&pi[1]),
        new_hash_lo: fr_to_u256(&pi[2]),
        new_hash_hi: fr_to_u256(&pi[3]),
        loss: fr_to_u256(&pi[4]),
        error_bound: fr_to_u256(&pi[5]),
        step_number: fr_to_u256(&pi[6]),
        error_checksum: if pi.len() > 7 { fr_to_u256(&pi[7]) } else { U256::zero() },
    };

    Some((result.proof.clone(), result.public_inputs.clone(), inputs))
}

// ============================================================================
// Integration Tests
// ============================================================================

/// End-to-end: generate a real Halo2 proof and verify it through
/// `VerifierNode` with `VerifyAll` policy.
#[tokio::test]
async fn test_real_proof_through_verifier_node() {
    let Some((proof_bytes, _pi_fr, inputs)) = generate_real_proof() else {
        eprintln!("Skipping test_real_proof_through_verifier_node: proof generation failed");
        return;
    };

    let config = VerifierConfig {
        policy: VerificationPolicy::VerifyAll,
        model_dims: Some((D_IN, D_HID, D_OUT)),
        ..Default::default()
    };
    let node = VerifierNode::new(PeerId::random(), config);

    let result = node.verify_proof("real-proof-1".into(), &proof_bytes, &inputs).await;
    assert!(
        result.is_valid(),
        "Real Halo2 proof should pass VerifyAll: {:?}",
        result
    );
}

/// Ensure that random bytes are rejected by `VerifierNode` with `VerifyAll`.
#[tokio::test]
async fn test_fake_proof_rejected_by_verifier_node() {
    let config = VerifierConfig {
        policy: VerificationPolicy::VerifyAll,
        model_dims: Some((D_IN, D_HID, D_OUT)),
        ..Default::default()
    };
    let node = VerifierNode::new(PeerId::random(), config);

    let fake_proof = vec![0xDE; 512];
    let inputs = TrainingProofInputs {
        old_hash_lo: U256::from(1),
        old_hash_hi: U256::from(2),
        new_hash_lo: U256::from(3),
        new_hash_hi: U256::from(4),
        loss: U256::from(100),
        error_bound: U256::from(10),
        step_number: U256::from(1),
        error_checksum: U256::zero(),
    };

    let result = node.verify_proof("fake-proof-1".into(), &fake_proof, &inputs).await;
    assert!(!result.is_valid(), "Fake proof should be rejected by VerifyAll");
    if let VerifyResult::Invalid(reason) = result {
        assert!(reason.contains("Halo2 KZG"), "Rejection reason should mention Halo2: {}", reason);
    }
}

/// End-to-end: generate a real Halo2 proof and verify it through
/// `ProofVerifier` (training/verification.rs pipeline).
#[tokio::test]
async fn test_real_proof_through_proof_verifier() {
    let Some((proof_bytes, pi_fr, _inputs)) = generate_real_proof() else {
        eprintln!("Skipping test_real_proof_through_proof_verifier: proof generation failed");
        return;
    };

    // Construct the proof+PI payload in the EVM-appended format that
    // ProofVerifier.parse_proof_and_inputs expects.
    let mut proof_with_pi = proof_bytes.clone();
    for fr in &pi_fr {
        use helix_prover::halo2curves::ff::PrimeField;
        let repr = fr.to_repr();
        let mut be_bytes = [0u8; 32];
        for (i, b) in repr.as_ref().iter().enumerate() {
            be_bytes[31 - i] = *b;
        }
        proof_with_pi.extend_from_slice(&be_bytes);
    }

    let config = VerificationConfig {
        model_dims: Some((D_IN, D_HID, D_OUT)),
        ..Default::default()
    };
    let verifier = ProofVerifier::with_model_dims(config, D_IN, D_HID, D_OUT);

    let result = verifier.verify_gradient_proof(
        &PeerId::random(),
        1,
        [0u8; 32],
        0.05,
        &proof_with_pi,
    ).await;

    assert!(
        result.is_valid,
        "Real proof should pass ProofVerifier: {:?}",
        result.error
    );
}

/// Verify that the proof cache key includes model commitment:
/// same proof with different commitments should cache independently.
#[tokio::test]
async fn test_cache_key_includes_model_commitment() {
    use helix_node::training::verification::VerificationPolicy as TVPolicy;

    let config = VerificationConfig {
        model_dims: Some((D_IN, D_HID, D_OUT)),
        policy: TVPolicy::StructuralOnly, // fast — we only care about caching behaviour
        enable_cache: true,
        ..Default::default()
    };
    let verifier = ProofVerifier::new(config);

    let proof = vec![0xAB; 128];
    let commitment_a = [0x11u8; 32];
    let commitment_b = [0x22u8; 32];

    // Verify with commitment A
    let r1 = verifier.verify_gradient_proof(
        &PeerId::random(), 1, commitment_a, 0.05, &proof,
    ).await;
    assert!(r1.is_valid);

    // Verify with commitment B — same proof bytes but different commitment.
    // This should NOT be a cache hit (commitment differs).
    let r2 = verifier.verify_gradient_proof(
        &PeerId::random(), 1, commitment_b, 0.05, &proof,
    ).await;
    assert!(r2.is_valid);

    let stats = verifier.stats();
    // Both verifications should have been independent (no cache hits)
    assert_eq!(stats.cache_hits, 0, "Same proof with different commitments must not share cache");
}
